# 断言
```
def foo(s):
    n = int(s)
    assert n != 0, 'n is zero!'
    return 10 / n

def main():
    foo('0')

# 解释器时可以用`-O`参数来关闭`assert`
# python -O err.py
$ python err.py  
Traceback (most recent call last):
  ...
AssertionError: n is zero!
```

# pdb（等价gdb）
- 启动Python的调试器pdb，让程序以单步方式运行
- 可以随时查看运行状态

```
# err.py
s = '0'
n = int(s)
print(10 / n)
```

```
$ python -m pdb err.py
> /Users/michael/Github/learn-python3/samples/debug/err.py(2)<module>()
-> s = '0'
(Pdb) l
  1     # err.py
  2  -> s = '0'
  3     n = int(s)
  4     print(10 / n)

(Pdb) n
> /Users/michael/Github/learn-python3/samples/debug/err.py(3)<module>()
-> n = int(s)
(Pdb) n
> /Users/michael/Github/learn-python3/samples/debug/err.py(4)<module>()
-> print(10 / n)

(Pdb) p s
'0'
(Pdb) p n
0

(Pdb) q
```

## pdb.set_trace()
```
# err.py
import pdb

s = '0'
n = int(s)
pdb.set_trace() # 运行到这里会自动暂停，并进入pdb调试环境
print(10 / n)
```